remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Heluca Project Blog
author: Robert Helewka
description: Posts about my IoT projects.
